### PR TITLE
Add python wrapper tests for Indexlr and RandomSequenceGenerator

### PR DESCRIPTION
**Pull request by lcoombe**
Adding a couple more tests for the python wrappers

### CODE REVIEW

**Comment by vlad0x00** [comment]
Just a stylistic remark, but my suggestion would be renaming `RandomSequenceGenerator` to something shorter (and equally understandable) like `RandSeqGenerator`, `RandomSeqGen`, or `RandomSeqGenerator`. The full name is a tad unwiedly.

**Comment by lcoombe** [comment]
Thanks for that suggestion Vlad - makes sense! We could look into doing that in a separate PR maybe?

**Comment by parham-k** [comment]
I'll rename the class to `RandomSeqGen` in another PR.

**Review by parham-k — COMMENTED** [review]
Thanks for the tests @lcoombe! Please just rename the test case classes and this'll be ready to merge.

**Review by parham-k — APPROVED** [review]

**Pull request merged**
