### PR TITLE
Fix mibf wrapper

### PR DESCRIPTION
**Pull request by parham-k**
Fix for multi-index Bloom filter's Python wrappers

### CODE REVIEW

**Comment by MurathanGoktas** [comment]
Nice work. I have already been doing progress on this issue and currently have an exhaustive testing script at 'wrappers-test' branch. You can test your wrapper modifications with that testing script.

**Comment by parham-k** [comment]
Sorry I didn't notice you had so much progress on this @MurathanGoktas. @jwcodee and I are working on the `aahash` branch, and regenerating the wrappers in `master` causes the issue in #86, which prevents btllib from compiling. When do you think we can merge your `wrapper_tests` branch into master if this is fixed there?

**Comment by MurathanGoktas** [comment]
No worries @parham-k. For mi-bf it is already tested and working at 'wrapper_tests'. My intention was to create PR when I made the tests for other classes available too.
However if it is critical we can already merge 'wrapper_tests' or @jwcodee can use the current latest commit from that branch.

**Comment by parham-k** [comment]
Addressed in #89

**Pull request closed without merging**
